# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yuan/workspace/yuan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yuan/workspace/yuan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuan/workspace/yuan/CMakeFiles /home/yuan/workspace/yuan/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yuan/workspace/yuan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

#=============================================================================
# Target rules for targets named yuan

# Build rule for target.
yuan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yuan
.PHONY : yuan

# fast build rule for target.
yuan/fast:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/build
.PHONY : yuan/fast

tests/test.o: tests/test.cc.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cc.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.o
.PHONY : tests/test.cc.o

tests/test.i: tests/test.cc.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cc.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.i
.PHONY : tests/test.cc.i

tests/test.s: tests/test.cc.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cc.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.s
.PHONY : tests/test.cc.s

tests/test_config.o: tests/test_config.cc.o

.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cc.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.o
.PHONY : tests/test_config.cc.o

tests/test_config.i: tests/test_config.cc.i

.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cc.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.i
.PHONY : tests/test_config.cc.i

tests/test_config.s: tests/test_config.cc.s

.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cc.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.s
.PHONY : tests/test_config.cc.s

tests/test_fiber.o: tests/test_fiber.cc.o

.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cc.o:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.o
.PHONY : tests/test_fiber.cc.o

tests/test_fiber.i: tests/test_fiber.cc.i

.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cc.i:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.i
.PHONY : tests/test_fiber.cc.i

tests/test_fiber.s: tests/test_fiber.cc.s

.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cc.s:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.s
.PHONY : tests/test_fiber.cc.s

tests/test_iomanager.o: tests/test_iomanager.cc.o

.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cc.o:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.o
.PHONY : tests/test_iomanager.cc.o

tests/test_iomanager.i: tests/test_iomanager.cc.i

.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cc.i:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.i
.PHONY : tests/test_iomanager.cc.i

tests/test_iomanager.s: tests/test_iomanager.cc.s

.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cc.s:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.s
.PHONY : tests/test_iomanager.cc.s

tests/test_scheduler.o: tests/test_scheduler.cc.o

.PHONY : tests/test_scheduler.o

# target to build an object file
tests/test_scheduler.cc.o:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.o
.PHONY : tests/test_scheduler.cc.o

tests/test_scheduler.i: tests/test_scheduler.cc.i

.PHONY : tests/test_scheduler.i

# target to preprocess a source file
tests/test_scheduler.cc.i:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.i
.PHONY : tests/test_scheduler.cc.i

tests/test_scheduler.s: tests/test_scheduler.cc.s

.PHONY : tests/test_scheduler.s

# target to generate assembly for a file
tests/test_scheduler.cc.s:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.s
.PHONY : tests/test_scheduler.cc.s

tests/test_thread.o: tests/test_thread.cc.o

.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cc.o:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.o
.PHONY : tests/test_thread.cc.o

tests/test_thread.i: tests/test_thread.cc.i

.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cc.i:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.i
.PHONY : tests/test_thread.cc.i

tests/test_thread.s: tests/test_thread.cc.s

.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cc.s:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.s
.PHONY : tests/test_thread.cc.s

tests/test_util.o: tests/test_util.cc.o

.PHONY : tests/test_util.o

# target to build an object file
tests/test_util.cc.o:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.o
.PHONY : tests/test_util.cc.o

tests/test_util.i: tests/test_util.cc.i

.PHONY : tests/test_util.i

# target to preprocess a source file
tests/test_util.cc.i:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.i
.PHONY : tests/test_util.cc.i

tests/test_util.s: tests/test_util.cc.s

.PHONY : tests/test_util.s

# target to generate assembly for a file
tests/test_util.cc.s:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.s
.PHONY : tests/test_util.cc.s

yuan/config.o: yuan/config.cc.o

.PHONY : yuan/config.o

# target to build an object file
yuan/config.cc.o:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/config.cc.o
.PHONY : yuan/config.cc.o

yuan/config.i: yuan/config.cc.i

.PHONY : yuan/config.i

# target to preprocess a source file
yuan/config.cc.i:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/config.cc.i
.PHONY : yuan/config.cc.i

yuan/config.s: yuan/config.cc.s

.PHONY : yuan/config.s

# target to generate assembly for a file
yuan/config.cc.s:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/config.cc.s
.PHONY : yuan/config.cc.s

yuan/fiber.o: yuan/fiber.cc.o

.PHONY : yuan/fiber.o

# target to build an object file
yuan/fiber.cc.o:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/fiber.cc.o
.PHONY : yuan/fiber.cc.o

yuan/fiber.i: yuan/fiber.cc.i

.PHONY : yuan/fiber.i

# target to preprocess a source file
yuan/fiber.cc.i:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/fiber.cc.i
.PHONY : yuan/fiber.cc.i

yuan/fiber.s: yuan/fiber.cc.s

.PHONY : yuan/fiber.s

# target to generate assembly for a file
yuan/fiber.cc.s:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/fiber.cc.s
.PHONY : yuan/fiber.cc.s

yuan/iomanager.o: yuan/iomanager.cc.o

.PHONY : yuan/iomanager.o

# target to build an object file
yuan/iomanager.cc.o:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/iomanager.cc.o
.PHONY : yuan/iomanager.cc.o

yuan/iomanager.i: yuan/iomanager.cc.i

.PHONY : yuan/iomanager.i

# target to preprocess a source file
yuan/iomanager.cc.i:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/iomanager.cc.i
.PHONY : yuan/iomanager.cc.i

yuan/iomanager.s: yuan/iomanager.cc.s

.PHONY : yuan/iomanager.s

# target to generate assembly for a file
yuan/iomanager.cc.s:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/iomanager.cc.s
.PHONY : yuan/iomanager.cc.s

yuan/log.o: yuan/log.cc.o

.PHONY : yuan/log.o

# target to build an object file
yuan/log.cc.o:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/log.cc.o
.PHONY : yuan/log.cc.o

yuan/log.i: yuan/log.cc.i

.PHONY : yuan/log.i

# target to preprocess a source file
yuan/log.cc.i:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/log.cc.i
.PHONY : yuan/log.cc.i

yuan/log.s: yuan/log.cc.s

.PHONY : yuan/log.s

# target to generate assembly for a file
yuan/log.cc.s:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/log.cc.s
.PHONY : yuan/log.cc.s

yuan/scheduler.o: yuan/scheduler.cc.o

.PHONY : yuan/scheduler.o

# target to build an object file
yuan/scheduler.cc.o:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/scheduler.cc.o
.PHONY : yuan/scheduler.cc.o

yuan/scheduler.i: yuan/scheduler.cc.i

.PHONY : yuan/scheduler.i

# target to preprocess a source file
yuan/scheduler.cc.i:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/scheduler.cc.i
.PHONY : yuan/scheduler.cc.i

yuan/scheduler.s: yuan/scheduler.cc.s

.PHONY : yuan/scheduler.s

# target to generate assembly for a file
yuan/scheduler.cc.s:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/scheduler.cc.s
.PHONY : yuan/scheduler.cc.s

yuan/thread.o: yuan/thread.cc.o

.PHONY : yuan/thread.o

# target to build an object file
yuan/thread.cc.o:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/thread.cc.o
.PHONY : yuan/thread.cc.o

yuan/thread.i: yuan/thread.cc.i

.PHONY : yuan/thread.i

# target to preprocess a source file
yuan/thread.cc.i:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/thread.cc.i
.PHONY : yuan/thread.cc.i

yuan/thread.s: yuan/thread.cc.s

.PHONY : yuan/thread.s

# target to generate assembly for a file
yuan/thread.cc.s:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/thread.cc.s
.PHONY : yuan/thread.cc.s

yuan/timer.o: yuan/timer.cc.o

.PHONY : yuan/timer.o

# target to build an object file
yuan/timer.cc.o:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/timer.cc.o
.PHONY : yuan/timer.cc.o

yuan/timer.i: yuan/timer.cc.i

.PHONY : yuan/timer.i

# target to preprocess a source file
yuan/timer.cc.i:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/timer.cc.i
.PHONY : yuan/timer.cc.i

yuan/timer.s: yuan/timer.cc.s

.PHONY : yuan/timer.s

# target to generate assembly for a file
yuan/timer.cc.s:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/timer.cc.s
.PHONY : yuan/timer.cc.s

yuan/util.o: yuan/util.cc.o

.PHONY : yuan/util.o

# target to build an object file
yuan/util.cc.o:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/util.cc.o
.PHONY : yuan/util.cc.o

yuan/util.i: yuan/util.cc.i

.PHONY : yuan/util.i

# target to preprocess a source file
yuan/util.cc.i:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/util.cc.i
.PHONY : yuan/util.cc.i

yuan/util.s: yuan/util.cc.s

.PHONY : yuan/util.s

# target to generate assembly for a file
yuan/util.cc.s:
	$(MAKE) -f CMakeFiles/yuan.dir/build.make CMakeFiles/yuan.dir/yuan/util.cc.s
.PHONY : yuan/util.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... test_iomanager"
	@echo "... rebuild_cache"
	@echo "... test_scheduler"
	@echo "... test_fiber"
	@echo "... test_util"
	@echo "... test_config"
	@echo "... test_thread"
	@echo "... test"
	@echo "... yuan"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_scheduler.o"
	@echo "... tests/test_scheduler.i"
	@echo "... tests/test_scheduler.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
	@echo "... tests/test_util.o"
	@echo "... tests/test_util.i"
	@echo "... tests/test_util.s"
	@echo "... yuan/config.o"
	@echo "... yuan/config.i"
	@echo "... yuan/config.s"
	@echo "... yuan/fiber.o"
	@echo "... yuan/fiber.i"
	@echo "... yuan/fiber.s"
	@echo "... yuan/iomanager.o"
	@echo "... yuan/iomanager.i"
	@echo "... yuan/iomanager.s"
	@echo "... yuan/log.o"
	@echo "... yuan/log.i"
	@echo "... yuan/log.s"
	@echo "... yuan/scheduler.o"
	@echo "... yuan/scheduler.i"
	@echo "... yuan/scheduler.s"
	@echo "... yuan/thread.o"
	@echo "... yuan/thread.i"
	@echo "... yuan/thread.s"
	@echo "... yuan/timer.o"
	@echo "... yuan/timer.i"
	@echo "... yuan/timer.s"
	@echo "... yuan/util.o"
	@echo "... yuan/util.i"
	@echo "... yuan/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

